name: Alfresco Keycloak CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MAVEN_SKIP_RC: "true"
  MAVEN_OPTS: "-Xms512m -Xmx1536m -Dmaven.wagon.http.retryHandler.count=3"
  MAVEN_SETTINGS: "maven-settings.xml"
  THEME_VERSION: "0.3.2"
  VERACODE_WRAPPER_SHA1: "57608b640b9ba3d39d906995e332f286d809cbab"
  VERACODE_WRAPPER_VERSION: "22.1.9.3"
  VERACODE_SANDBOX: "KeycloakFork"
  JAVA_VERSION: "8"

jobs:
  veracode:
    name: "Veracode SCA"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.36.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-settings: ${{ env.MAVEN_SETTINGS }}
      - name: "Veracode SCA"
        run: bash .ci/source_clear.sh
        continue-on-error: true
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      - name: "Clean Maven cache"
        run: |
          rm -rf $HOME/.m2/repository/org/keycloak
          rm -rf $HOME/.m2/repository/org/wildfly
          rm -rf $HOME/.m2/repository/org/jboss
          rm -rf $HOME/.m2/repository/org/alfresco

  veracode_static:
    name: "Veracode Static Scan"
    runs-on: ubuntu-latest
    needs: [veracode]
    if: ${{ contains(github.event.head_commit.message, '[static scan]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.36.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.36.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-settings: ${{ env.MAVEN_SETTINGS }}
      - name: "Set GIT_TAG"
        run: |
          if [[ "${{ github.ref }}" =~ refs/tags/.+ ]]; then
            echo "GIT_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi
      - name: "Download Veracode Wrapper"
        run: bash .ci/static_analysis_init.sh
      - name: "Build Keycloak"
        run: bash .ci/build-server.sh
      - name: "Add Alfresco Keycloak Theme"
        run: |
          source .ci/add-alfresco-theme.sh
          echo "ARTIFACT_TO_SCAN=${ARTIFACT_TO_SCAN}" >> $GITHUB_ENV
      - name: "Veracode Static Scan"
        run: bash .ci/static_analysis.sh
        env:
          VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
      - name: "Clean Maven cache"
        run: |
          rm -rf $HOME/.m2/repository/org/keycloak
          rm -rf $HOME/.m2/repository/org/wildfly
          rm -rf $HOME/.m2/repository/org/jboss
          rm -rf $HOME/.m2/repository/org/alfresco

  tests:
    name: "${{ matrix.test-suite }} tests"
    runs-on: ubuntu-latest
    needs: [veracode_static]
    if: >
      !(failure() || cancelled()) &&
      !contains(github.event.head_commit.message, '[skip tests]')
    strategy:
      fail-fast: false
      matrix:
        include:
          - test-suite: unit
          - test-suite: server-group1
          - test-suite: server-group2
          - test-suite: server-group3
          - test-suite: server-group4
          - test-suite: adapter-tests
          - test-suite: adapter-tests-authz
          - test-suite: crossdc-server
          - test-suite: crossdc-adapter
          - test-suite: broker
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.36.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.36.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-settings: ${{ env.MAVEN_SETTINGS }}
      - name: "Test"
        run: bash .ci/run-tests.sh ${{ matrix.test-suite }}
      - name: "Clean Maven cache"
        run: |
          rm -rf $HOME/.m2/repository/org/keycloak
          rm -rf $HOME/.m2/repository/org/wildfly
          rm -rf $HOME/.m2/repository/org/jboss
          rm -rf $HOME/.m2/repository/org/alfresco

  deploy:
    name: "Release Alfresco Keycloak"
    runs-on: ubuntu-latest
    needs: [tests]
    if: >
      !(failure() || cancelled()) &&
      startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.36.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.36.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-settings: ${{ env.MAVEN_SETTINGS }}
      - name: "Clean Maven cache"
        run: |
          rm -rf $HOME/.m2/repository/org/keycloak
          rm -rf $HOME/.m2/repository/org/wildfly
          rm -rf $HOME/.m2/repository/org/jboss
          rm -rf $HOME/.m2/repository/org/alfresco
      - name: "Set GIT_TAG"
        run: echo "GIT_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: "Build Keycloak"
        run: bash .ci/build-server.sh
      - name: "Add Alfresco Keycloak Theme"
        run: bash .ci/add-alfresco-theme.sh
      - name: "Upload Release Asset"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $GIT_TAG -t $GIT_TAG
          gh release upload $GIT_TAG distribution/server-dist/target/keycloak-$GIT_TAG.zip
